//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
        }
    
        public string Id { get; set; }
        public string CountryId { get; set; }
        public Nullable<decimal> Level1Id { get; set; }
        public Nullable<decimal> Level2Id { get; set; }
        public string CityEngName { get; set; }
        public string CityArbName { get; set; }
        public string Index { get; set; }
        public string AdditionalInfo { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string Level1Text { get; set; }
        public string Level2Text { get; set; }
    
        public Country Country { get; set; }
        public EgyptFirstLevel Level1 { get; set; }
        public EgyptSecondLevel Level2 { get; set; }
    }
}
