//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Application()
        {
        }
    
        public string Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public int DateOfBirth { get; set; }
        public string Pin { get; set; }
        public string RepresentativeType { get; set; }
        public string SexId { get; set; }
        public string MaritalId { get; set; }
        public string ReligionId { get; set; }
        public string FilingDocReasonId { get; set; }
        public string MotherId { get; set; }
        public string FatherId { get; set; }
        public string AnotherRepresentId { get; set; }
        public string BirthCertificateId { get; set; }
        public string BirthCertActionId { get; set; }
        public string IdCardV0Id { get; set; }
        public string IdCardActionId { get; set; }
        public string DriverLicenseId { get; set; }
        public string DLActionId { get; set; }
        public string ForeignPassportId { get; set; }
        public string FPActionId { get; set; }
        public string HusbandId { get; set; }
        public string IssuedIdCardId { get; set; }
        public string BirthPlaceId { get; set; }
        public string LivingPlaceId { get; set; }
        public string BusinessActivityId { get; set; }
        public string MilitaryDutyId { get; set; }
        public string EducationId { get; set; }
        public string VotingPlaceId { get; set; }
        public string UrgentTypeId { get; set; }
        public string BiometricsId { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneWork { get; set; }
        public string Issuer { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }
    
        public Religion Religion { get; set; }
        public Address BirthPlace { get; set; }
        public Address LivingPlace { get; set; }
        public PARAM BirthCertAction { get; set; }
        public Biometrics Biometrics { get; set; }
        public BirthCertificate BirthCertificate { get; set; }
        public BusinessActivity BusinessActivity { get; set; }
        public DriverLicense DriverLicense { get; set; }
        public PARAM DLAction { get; set; }
        public Education Education { get; set; }
        public PARAM FPAction { get; set; }
        public Representative Husband { get; set; }
        public PARAM IdCardAction { get; set; }
        public PARAM Marital { get; set; }
        public MilitaryDuty MilitaryDuty { get; set; }
        public PARAM FilingDocReason { get; set; }
        public PARAM Sex { get; set; }
        public PARAM UrgentType { get; set; }
        public Representative Father { get; set; }
        public Representative Mother { get; set; }
        public Representative AnotherRepresent { get; set; }
        public Address VotingPlace { get; set; }
        public ForeignPassport ForeignPassport { get; set; }
        public IdCard IssuedIdCard { get; set; }
        public IdCard IdCardV0 { get; set; }
    }
}
