//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BirthCertificate()
        {
        }
    
        public string Id { get; set; }
        public string Serial { get; set; }
        public string Number { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string SexId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssueAuthor { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string AdditionalInfo { get; set; }
        public int BirthDate { get; set; }
        public string Pin { get; set; }
        public string ScanId { get; set; }
    
        public PARAM Sex { get; set; }
        public ScannedDocument Scan { get; set; }
    }
}
