//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusinessActivity()
        {
        }
    
        public string Id { get; set; }
        public string ProfessionId { get; set; }
        public string Workplace { get; set; }
        public string EmployerName { get; set; }
        public Nullable<System.DateTime> StartWork { get; set; }
        public string CommerceOffice { get; set; }
        public string Registrynumber { get; set; }
        public System.DateTime DateIncert { get; set; }
    
        public  Profession Profession { get; set; }
    }
}
