//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DLStatus
    {
        public string DriverLicenseId { get; set; }
        public string RepresentativeStatusId { get; set; }
        public System.DateTime DateInsert { get; set; }
        public Nullable<System.DateTime> DateFact { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<int> BisNotified { get; set; }
        public string Id { get; set; }
        public Nullable<System.Guid> AuthorGuid { get; set; }
    
        public DriverLicense DriverLicense { get; set; }
        public Representative RepresentativeStatus { get; set; }
    }
}
