//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdCard()
        {
        }
    
        public string Id { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string SexId { get; set; }
        public int DateBirth { get; set; }
        public string Pin { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string BirthCountry { get; set; }
        public string BirthDetails { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string MaritalStatusId { get; set; }
        public string Profession { get; set; }
        public string AdditionalInfo { get; set; }
        public string IssuedAuthor { get; set; }
        public string Religion { get; set; }
        public string BiometricsId { get; set; }
        public bool IsOur { get; set; }
        public string ScanId { get; set; }
    
        public PARAM MaritalStatus { get; set; }
        public ScannedDocument Scan { get; set; }
        public PARAM Sex { get; set; }
        public Biometrics Biometrics { get; set; }
    }
}
