//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryDuty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MilitaryDuty()
        {
        }
    
        public string Id { get; set; }
        public string StatusId { get; set; }
        public string ServiceId { get; set; }
        public Nullable<System.DateTime> RecruitDate { get; set; }
        public System.DateTime DateInsert { get; set; }
    
        public PARAM Service { get; set; }
        public PARAM Status { get; set; }
    }
}
