//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPayment()
        {
        }
    
        public string Id { get; set; }
        public string ApplicationId { get; set; }
        public decimal Amount { get; set; }
        public string Account { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string Purpose { get; set; }
        public string Receiver { get; set; }
        public string Privelege { get; set; }
        public System.DateTime DateInsert { get; set; }
        public string ScanId { get; set; }
        public string PaymentTypeId { get; set; }
    
        public Application Application { get; set; }
        public ScannedDocument Scan { get; set; }
        public PARAM PaymentType { get; set; }
    }
}
