//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAM
    {
        public PARAM()
        {
        }
    
        public string Id { get; set; }
        public string Domain { get; set; }
        public string ValueEng { get; set; }
        public string ValueArb { get; set; }
        public string Label { get; set; }
        public string Note { get; set; }
    }
}
