//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalizationResponse
    {
        public string Id { get; set; }
        public string ApplicationId { get; set; }
        public string ResultId { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string SexId { get; set; }
        public Nullable<int> BirthDate { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Similarity { get; set; }
        public string AdditionalInfo { get; set; }
        public string BisQueue { get; set; }
        public string BisNumber { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<System.DateTime> DateReceive { get; set; }
    
        public Application Application { get; set; }
        public PARAM Result { get; set; }
        public PARAM Sex { get; set; }
    }
}
