//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDCard.Data.IdCardEFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representative
    {
        public string Id { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string SexId { get; set; }
        public Nullable<int> DateOfBirth { get; set; }
        public string IdCardId { get; set; }
        public string DriverLicenseId { get; set; }
        public string ForegnPassId { get; set; }
    
        public DriverLicense DriverLicense { get; set; }
        public PARAM Sex { get; set; }
        public ForeignPassport ForeignPassport { get; set; }
        public IdCard IdCard { get; set; }
    }
}
